### ISSUE TITLE
Allow custom `net.Listener`

### ISSUE THREAD

**Issue by Davincible** [loopholelabs/frisbee-go#155]
My problem with the current API is the `Start` method, as it only takes an address string. I understand the convenience of this, but would also really like a function to pass a custom `net.Listener`. So essentially I'm asking for something like exposing `s.handleListener()`.

A current workaround could probably be to manually implement that method, but it's a bit of a hack.

**Comment by ShivanshVij** [comment]
I think that’s a fair request. I’ll take a look tomorrow to see if there’s an obvious way to do this.

For now, there is a ‘ServeConn’ method you can use - just create an accept loop and call ServeConn on the accepted connection.

**Comment by Davincible** [comment]
@ShivanshVij thanks!

**Comment by ShivanshVij** [comment]
Closed as part of `v0.7.2`
